# Generated by Django 3.1 on 2020-08-30 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulkInd', models.BooleanField()),
                ('brand', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=3)),
                ('initialPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowestPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acceptedInd', models.BooleanField()),
            ],
        ),
    ]
